<a href="https://colab.research.google.com/github/BiancadeFrancisco/RedeNeural_Churn/blob/main/REDE_NEURAL_PR%C3%81TICA_DESAFIO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# VOCÊ RECEBERÁ UMA BASE REFERENTE A CHURN, ONDE A SUA VARIÁVEL TARGET SERÁ A CHURN. FAÇA O TREINAMENTO E USE A ATIVAÇÃO LOGISTIC (SIGMOIDE), E ANALISAR A ACURÁCIA DA SAÍDA:

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/churn_data.xlsx")

df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer,42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.describe()

            tenure  MonthlyCharges
count  7042.000000     7042.000000
mean     32.366373       64.755886
std      24.557955       30.088238
min       0.000000       18.250000
25%       9.000000       35.500000
50%      29.000000       70.350000
75%      55.000000       89.850000
max      72.000000      118.750000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7042 entries, 0 to 7041
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7042 non-null   object
 1   tenure            7042 non-null   int64
 2   PhoneService      7042 non-null   object
 3   Contract          7042 non-null   object
 4   PaperlessBilling  7042 non-null   object
 5   PaymentMethod     7042 non-null   object
 6   MonthlyCharges    7042 non-null   float64
 7   TotalCharges      7042 non-null   object
 8   Churn             7042 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 495.3+ KB

In [ ]:
# NESSE CASO A COLUNA customerID NÃO É NECESSÁRIA, PODEMOS EXCLUI-LA:

df.drop(columns=["customerID"])

,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,45,No,One year,No,Bank transfer,42.30,1840.75,No
4,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...
7037,72,Yes,Two year,Yes,Bank transfer,21.15,1419.4,No
7038,24,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,72,Yes,One year,Yes,Credit card,103.20,7362.9,No
7040,11,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,4,Yes,Month-to-month,Yes,Mailed check,74.40,306.6,Yes

In [ ]:
# EXCLUIR REGISTROS NULOS DA BASE DE DADOS:

df = df.dropna()

In [ ]:
df.isnull().any()

customerID          False
tenure              False
PhoneService        False
Contract            False
PaperlessBilling    False
PaymentMethod       False
MonthlyCharges      False
TotalCharges        False
Churn               False
dtype: bool

In [ ]:
# TRANSFORMAR VARIÁVEIS OBJECT EM NUMÉRICAS:

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors = "coerce")

In [ ]:
# SEPARAR VARIÁVEIS NUMÉRICAS E CATEGÓRICAS:

cat_vars = ["PhoneService", "Contract", "PaperlessBilling","PaymentMethod"]

num_vars = ["tenure", "MonthlyCharges", "TotalCharges"]

modeling_vars = cat_vars + num_vars

In [ ]:
# DISTRIBUIR X E Y:

x = df.filter(modeling_vars).copy()

y = df["Churn"].copy()

y = pd.DataFrame(y)

In [ ]:
# TRANSFORMAR COLUNA "CHURN" EM FORMATO BINÁRIO:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y.Churn)

y.Churn = le.transform(y.Churn)

In [ ]:
y

      Churn
0         0
1         0
2         1
3         0
4         1
...     ...
7037      0
7038      0
7039      0
7040      0
7041      1

[7031 rows x 1 columns]

In [ ]:
# TRANSFORMAR VARIÁVEIS CATEGÓRICAS DO X EM DUMMIES:

x = pd.get_dummies(x)

In [ ]:
x

,tenure,MonthlyCharges,TotalCharges,PhoneService_No,PhoneService_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,29.85,29.85,1,0,1,0,0,0,1,0,0,1,0
1,34,56.95,1889.50,0,1,0,1,0,1,0,0,0,0,1
2,2,53.85,108.15,0,1,1,0,0,0,1,0,0,0,1
3,45,42.30,1840.75,1,0,0,1,0,1,0,1,0,0,0
4,2,70.70,151.65,0,1,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7037,72,21.15,1419.40,0,1,0,0,1,0,1,1,0,0,0
7038,24,84.80,1990.50,0,1,0,1,0,0,1,0,0,0,1
7039,72,103.20,7362.90,0,1,0,1,0,0,1,0,1,0,0
7040,11,29.60,346.45,1,0,1,0,0,0,1,0,0,1,0
7041,4,74.40,306.60,0,1,1,0,0,0,1,0,0,0,1

In [ ]:
# VERIFICAR A DISTRIBUIÇÃO DA NOSSA VARIÁVEL TARGET:

df["Churn"].value_counts() # resultado: não 5173, sim 1869

No     5162
Yes    1869
Name: Churn, dtype: int64

In [ ]:
# SEPARAR TREINO E TESTE:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test, = train_test_split(x, y, test_size=0.2)

In [ ]:
# FAZER NORMALIZAÇÃO DAS NOSSAS VARIÁVEIS:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [ ]:
# TRANSFORMAR TUDO EM DATAFRAME:

X_train = pd.DataFrame(X_train_scaled, columns = X_train.columns)

X_test = pd.DataFrame(X_test_scaled, columns = X_test.columns)

In [ ]:
# IMPLEMENTAR A REDE NEURAL:

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

clf = MLPClassifier(hidden_layer_sizes = (100, 50, 20), activation = "logistic")
# hiperparâmetro (camadas escondidas = "hidden_layer_sizes = (100, 50, 20)") e a função de ativação (sigmoide = "activation = "logistic")

clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

MLPClassifier(activation='logistic', hidden_layer_sizes=(100, 50, 20))

In [ ]:
# VERIFICAR A ACURÁCIA E O F1 DO MODELO:

y_pred = clf.predict(X_test)
print(f"Acurácia: {accuracy_score(y_test, y_pred)*100}%")
print(f"F1 Score: {f1_score(y_test, y_pred)*100}%")

Acurácia: 79.24662402274343%
F1 Score: 57.058823529411775%